UPDATE wp_posts SET post_excerpt = 'Moteles para parejas en Santiago: ubicación, acceso y opciones para una estadía privada en la ciudad.' WHERE ID = 11444;
UPDATE wp_posts SET post_excerpt = 'Moteles cerca del aeropuerto de Santiago con información útil para elegir una opción de descanso cercana.' WHERE ID = 11199;
UPDATE wp_posts SET post_excerpt = 'Moteles cerca del aeropuerto de Concepción para revisar ubicación, acceso y conveniencia según tu ruta.' WHERE ID = 11883;
UPDATE wp_posts SET post_excerpt = 'Moteles cerca del Terminal Collao en Concepción con datos prácticos para llegar y descansar con facilidad.' WHERE ID = 11209;
UPDATE wp_posts SET post_excerpt = 'Moteles en La Serena cerca del aeropuerto, pensados para una estadía breve con buena conexión urbana.' WHERE ID = 11211;
UPDATE wp_posts SET post_excerpt = 'Moteles en La Cisterna, sector Américo Vespucio y Gran Avenida, con foco en ubicación y acceso.' WHERE ID = 11435;
UPDATE wp_posts SET post_excerpt = 'Motel en Maipú con acceso rápido y una ubicación útil para una estadía corta o de paso.' WHERE ID = 1968;
UPDATE wp_posts SET post_excerpt = 'Motel en Providencia con ubicación central y datos clave para evaluar comodidad y acceso.' WHERE ID = 1996;
UPDATE wp_posts SET post_excerpt = 'Motel en San Miguel con información práctica sobre ubicación, acceso y tipo de estadía.' WHERE ID = 2032;
UPDATE wp_posts SET post_excerpt = 'Motel en Santiago con enfoque en privacidad, conexión y conveniencia dentro de la ciudad.' WHERE ID = 2037;
UPDATE wp_posts SET post_excerpt = 'Motel en Recoleta con acceso simple y referencias útiles para una pausa o estadía breve.' WHERE ID = 2695;
UPDATE wp_posts SET post_excerpt = 'Motel en Quinta Normal, sector Carrascal, con datos para ubicarlo y evaluar su conveniencia.' WHERE ID = 2040;
UPDATE wp_posts SET post_excerpt = 'Motel en Pudahuel con ubicación estratégica para quienes buscan descanso cerca de rutas principales.' WHERE ID = 2484;
UPDATE wp_posts SET post_excerpt = 'Motel en San Bernardo con información de acceso y contexto local para una estadía práctica.' WHERE ID = 2152;
UPDATE wp_posts SET post_excerpt = 'Motel en Viña del Mar con referencia de ubicación y servicios para una estadía breve.' WHERE ID = 2933;
UPDATE wp_posts SET post_excerpt = 'Motel en Valparaíso con datos útiles sobre acceso, entorno y comodidad general.' WHERE ID = 2611;
UPDATE wp_posts SET post_excerpt = 'Motel en Temuco con información básica para revisar ubicación y conveniencia.' WHERE ID = 3087;
UPDATE wp_posts SET post_excerpt = 'Motel en Puerto Montt con enfoque en acceso, ubicación y estadía de corta duración.' WHERE ID = 3063;
UPDATE wp_posts SET post_excerpt = 'Motel en Viña del Mar con referencias de ubicación y utilidad para moverse por la ciudad.' WHERE ID = 2664;
UPDATE wp_posts SET post_excerpt = 'Motel Luz de Luna en El Monte con información de ubicación y referencia local.' WHERE ID = 2173;
UPDATE wp_posts SET post_excerpt = 'Cabañas y motel Los Placeres en Placilla con foco en acceso, ubicación y estadía.' WHERE ID = 2905;
UPDATE wp_posts SET post_excerpt = 'Motel Krisaos en Calle Larga con datos útiles para evaluar su ubicación y conveniencia.' WHERE ID = 2637;
UPDATE wp_posts SET post_excerpt = 'Motel Sanit Valentine en Pere Las Casas con referencia local y enfoque práctico.' WHERE ID = 2899;
UPDATE wp_posts SET post_excerpt = 'Motel en Bulnes con datos de ubicación y una referencia útil para estadías breves.' WHERE ID = 11107;
UPDATE wp_posts SET post_excerpt = 'Motel Caracol con información básica para ubicarlo y revisar su conveniencia.' WHERE ID = 10746;
UPDATE wp_posts SET post_excerpt = 'Motel Bella Luna con enfoque en acceso, contexto local y estadía discreta.' WHERE ID = 10736;
UPDATE wp_posts SET post_excerpt = 'Motel Capricho con datos prácticos para revisar ubicación y tipo de servicio.' WHERE ID = 10741;
UPDATE wp_posts SET post_excerpt = 'Motel Artis con referencia de acceso y utilidad para una pausa cómoda.' WHERE ID = 2685;
UPDATE wp_posts SET post_excerpt = 'Motel Bahía Velero en Penco o Tomé con contexto local y datos de ubicación.' WHERE ID = 3092;
UPDATE wp_posts SET post_excerpt = 'Motel Bellas Artes Palace en Santiago con información útil sobre acceso y entorno.' WHERE ID = 2613;
